# Generated by Django 4.0.4 on 2022-05-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ELEV8APP', '0002_header'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Header',
        ),
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog_image'),
        ),
    ]
