# Generated by Django 4.0.4 on 2022-05-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ELEV8APP', '0003_delete_header_topic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
