# Generated by Django 4.0.4 on 2022-05-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ELEV8APP', '0004_topic_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-id']},
        ),
    ]
