# Generated by Django 4.0.4 on 2022-05-29 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ELEV8APP', '0006_content_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content_post',
            old_name='header',
            new_name='title',
        ),
    ]
